# syntax=docker/dockerfile:1.4
FROM python:3.8-alpine
RUN adduser -D microblog

WORKDIR /home/microblog

# COPY . .
COPY app app
COPY migrations migrations
COPY requirements requirements
COPY requirements.txt microblog.py boot.sh ./


ENV FLASK_APP microblog.py

RUN apk update && apk add --no-cache libcrypto3 libexpat && apk upgrade --no-cache

RUN <<-EOF
python -m venv .venv
.venv/bin/pip3 install -r requirements.txt
chmod +x boot.sh
chown -R microblog:microblog ./
EOF

USER microblog

HEALTHCHECK --interval=30s --timeout=10s --retries=3 CMD curl --fail http://localhost:5000/ || exit 1


EXPOSE 5000
ENTRYPOINT ["./boot.sh"]