---
sg_groups:
    -   name: loadbalancer
        port_rules:
        -   name: SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound
            source_address_prefix: '0.0.0.0/0'
        -   name: HTTP
            protocol: Tcp
            destination_port_range: 80
            access: Allow
            priority: 1002
            direction: Inbound
            source_address_prefix: '0.0.0.0/0'
        -   name: HTTPS
            protocol: Tcp
            destination_port_range: 443
            access: Allow
            priority: 1003
            direction: Inbound
            source_address_prefix: '0.0.0.0/0'
    -   name: appserver
        port_rules:
        -   name: SSH # APP
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound
            source_address_prefix: '0.0.0.0/0'
        -   name: HTTP
            protocol: Tcp
            destination_port_range: 8000
            access: Allow
            priority: 1002
            direction: Inbound
            source_address_prefix: '0.0.0.0/0'
    -   name: database
        port_rules:
        -   name: SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound
            source_address_prefix: "{{ groups['appserver'][0] }}/32" # '0.0.0.0/0'
        -   name: MYSQL
            protocol: Tcp
            destination_port_range: 3306
            access: Allow
            priority: 1002
            direction: Inbound
            source_address_prefix: "{{ groups['appserver'][0] }}/32" # '0.0.0.0/0'